version: '3'

services:
    jekyll:
        build:
            context: .././
            dockerfile: docker/jekyll/Dockerfile
        ports:
            - "4000:4000"
        volumes:
            - ../.:/var/www/app
        tty: true
        stdin_open: true

    nginx:
        build:
            context: ./nginx/
        restart: on-failure
        ports:
            - "80:80"
        volumes:
            - ../.:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - jekyll
